#配置中心
config-manager:
  appName: perf_prod
  mode: 0
  baseFolder: '/u01/config/'
  remoteCheckInterval: 10
  remoteUrl: 'http://inside-cnodeprod.hqzhuanche.com/rpc/download'
  remoteToken: 7p0i4g2r
  connectTimeout: 1000
  readTimeout: 1000